name: "minecraft-deploy"
# on:
#   schedule: 
#   - cron: '*/5 * * * *'
on: push

jobs:
  my-job:
    name: get config
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: get config
      run: |
        uname -a
        ls -la
        # sudo screen -S latest.legendsandmasters.nl -X quit
        # sudo git clone https://github.com/CoolZeroNL/minecraft-01-latest-pub-config.git
        # cp minecraft-01-latest-pub-config/* /home/minecraft/deployed/minecraft-00/
        # cp -R minecraft-01-latest-pub-config/* /home/minecraft/deployed/minecraft-00/
        # cd /home/minecraft/deployed/minecraft-00
        
