name: "minecraft-deploy"
# on:
#   schedule: 
#   - cron: '*/5 * * * *'
on: push

jobs:
  _01-ci_skip:
    runs-on: self-hosted
    steps:
    - name: Skip based on commit message
      uses: veggiemonk/skip-commit@1.0.0

  _02-checkout:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

  _03-check-deploy:
    runs-on: self-hosted
    steps:
    - name: check deploy
      run: |
        uname -a

  _04-check-connected:
    runs-on: self-hosted
    steps:
    - name: check deploy
      run: |
        uname -a

  _05-check-process:
    runs-on: self-hosted
    steps:
    - name: check deploy
      run: |
        uname -a

  _06-backup-all:
    runs-on: self-hosted
    steps:
    - name: check deploy
      run: |
        uname -a

  _07-backup-world:
    runs-on: self-hosted
    steps:
    - name: check deploy
      run: |
        uname -a
        
  _08-deploy:
    runs-on: self-hosted
    steps:
    - name: check deploy      
      run: |
        uname -a 
        # sudo rsync -a --exclude '.git' --exclude '.github' ./ /home/minecraft/deployed/minecraft-01-latest/    
        # sudo chown -R minecraft: /home/minecraft/deployed/        
        
  _09-deploy-checks:
    runs-on: self-hosted
    steps:
    - name: check deploy      
      run: |
        uname -a
        
  _10-start-server:
    runs-on: self-hosted
    steps:
    - name: check deploy      
      run: |
        uname -a        
        
# jobs:
#   my-job:
#   my-job:
#     name: get config
#     runs-on: self-hosted
#     steps:
#     - uses: actions/checkout@v1
#     - name: get config
#       run: |
#         # uname -a
#         # ls -la
#         # sudo screen -S latest.legendsandmasters.nl -X quit
#         sudo rsync -a --exclude '.git' --exclude '.github' ./ /home/minecraft/deployed/minecraft-01-latest/
#         # sudo ls -la /home/minecraft/deployed/minecraft-01-latest 
#         # sudo cat /home/minecraft/deployed/minecraft-01-latest/settings.cfg     
#         sudo chown -R minecraft: /home/minecraft/deployed/
